version: '3'
services:
  tcg:
    build: ./docker/tcg
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "8888:8888"
    volumes:
      - .:/home/tfuser/shared

  te:
    build: ./docker/te
    platform: linux/arm64/v8
    user: root
    ports:
      - "5555:5555"
    volumes:
      - .:/home/jovyan/work/