version: '3'
services:
  tcg:
    build: ./docker/tcg
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "8888:8888"
    volumes:
      - .:/home/tfuser/shared

  te:
    build: ./docker/te
    user: root
    ports:
      - "5000:5000"
    volumes:
      - .:/home/jovyan/work/