#!/usr/bin/env python3

import os,sys
import pandas as pd
from thermocodegen.coder import coder

sys.path.append(os.path.join(os.path.dirname(__file__), os.path.pardir, 'python'))
from tcg_slb.endmember import SLBEndmember

def generate_endmembers(outdir,stixrude_version):
  reference= 'generate_endmembers' 

  em_postfix = "_stx21_em" if stixrude_version == 21 else "_slb_em"
  csvfilename = "stx21ver.csv" if stixrude_version == 21 else "slb_endmembers.csv"

  df = pd.read_csv(os.path.join(os.path.dirname(__file__), os.path.pardir, 'database', 'data', csvfilename), skipinitialspace=True)

  try:
      os.mkdir(outdir)
  except FileExistsError:
      pass

  for i, row in df.iterrows():
      values_dict = row.to_dict()
      # clean up names to make them coder compliant
      name = values_dict.pop('name').replace('-','_')+em_postfix
      formula = values_dict.pop('formula')
      em = SLBEndmember(name,formula,reference,**values_dict)
      print(em.param_unit)
      print(em.tofile(outdir))

if __name__ == "__main__":
    import argparse
    import os

    parser = argparse.ArgumentParser( \
                           description="""Generate emmls for SLB thermodynamic database.""")
    parser.add_argument('-o', '--outdir', action='store', metavar='outdir', 
                        default=os.path.join(os.path.dirname(__file__), os.path.pardir, 'database', 'endmembers'), type=str, required=False,
                        help='Output directory for emml files (defaults to ../database/endmembers relative to script).')
    parser.add_argument('-v', '--stixrude_version', action="store", metavar="stixrude_version", default=11, type=int, required=False, help='Version of the Stixrude database as an integer (defaults to 11 for 2011).')
    args = parser.parse_args()

    generate_endmembers(args.outdir, args.stixrude_version)
