#%Module1.0
proc ModulesHelp { } {
        global dotversion

        puts stderr "	Sets environment for custom thermocodegen libraries."
}
module-whatis "Sets environment for interaction with custom thermocodegen libraries"


# Standard paths
setenv	  LIB_PREFIX				/home/tfuser/shared/systems/fo_fa/reactions/fo_fa_binary
prepend-path	  LIBRARY_PATH			/home/tfuser/shared/systems/fo_fa/reactions/fo_fa_binary/lib

prepend-path  PYTHONPATH		     /home/tfuser/shared/systems/fo_fa/reactions/fo_fa_binary/lib/python3.8/site-packages
prepend-path  LD_LIBRARY_PATH	     /home/tfuser/shared/systems/fo_fa/reactions/fo_fa_binary/lib
prepend-path  CPLUS_INCLUDE_PATH  /home/tfuser/shared/systems/fo_fa/reactions/fo_fa_binary/include:/home/tfuser/shared/systems/fo_fa/reactions/fo_fa_binary/include/coder
