#!/usr/bin/env python3

import os,sys
import pandas as pd
import ast
import numpy as np
import sympy as sym
from collections import OrderedDict
from thermocodegen.coder import coder

dbfile = os.path.join(os.path.pardir, 'database', 'tcg_slb_database.tar.gz')
dbpath = "file://{}".format(dbfile)
print(dbpath)

sys.path.append(os.path.join(os.path.dirname(__file__), os.path.pardir, 'python'))
from tcg_slb.reactions import SLBReactions

reference = "generate_reactions"

os.chdir(os.path.abspath(os.path.dirname(__file__)))

def generate_reactions(outdir):
    #################################################################
    # All Low P MgFeSiO4 reactions
    phases = ['Olivine', 'Wadsleyite', 'Ringwoodite', \
              'MgFePerovskite', 'Magnesiowuestite', 'Stishovite']
    reactions = []
    reactions.append(([['Olivine','Forsterite']],
                      [['Wadsleyite','MgWadsleyite']]))
    reactions.append(([['Olivine','Fayalite']],
                      [['Wadsleyite','FeWadsleyite']]))
    reactions.append(([['Olivine','Forsterite']],
                      [['Ringwoodite','MgRingwoodite']]))
    reactions.append(([['Olivine','Fayalite']],
                      [['Ringwoodite','FeRingwoodite']]))
    reactions.append(([['Wadsleyite','MgWadsleyite']],
                      [['Ringwoodite','MgRingwoodite']]))
    reactions.append(([['Wadsleyite','FeWadsleyite']],
                      [['Ringwoodite','FeRingwoodite']]))
    reactions.append(([['Olivine','Forsterite']],
                      [['MgFePerovskite','MgPerovskite'],
                       ['Magnesiowuestite','Periclase']]))
    reactions.append(([['Olivine','Fayalite']],
                      [['MgFePerovskite','FePerovskite'],
                       ['Magnesiowuestite','Wuestite']]))
    reactions.append(([['Olivine','Forsterite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['Olivine','Fayalite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['Wadsleyite','MgWadsleyite']],
                      [['MgFePerovskite','MgPerovskite'],
                       ['Magnesiowuestite','Periclase']]))
    reactions.append(([['Wadsleyite','FeWadsleyite']],
                      [['MgFePerovskite','FePerovskite'],
                       ['Magnesiowuestite','Wuestite']]))
    reactions.append(([['Wadsleyite','MgWadsleyite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['Wadsleyite','FeWadsleyite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['Ringwoodite','MgRingwoodite']],
                      [['MgFePerovskite','MgPerovskite'],
                       ['Magnesiowuestite','Periclase']]))
    reactions.append(([['Ringwoodite','FeRingwoodite']],
                      [['MgFePerovskite','FePerovskite'],
                       ['Magnesiowuestite','Wuestite']]))
    reactions.append(([['Ringwoodite','MgRingwoodite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['Ringwoodite','FeRingwoodite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['MgFePerovskite','MgPerovskite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['MgFePerovskite','FePerovskite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Stishovite','Stishovite']]))
    reactions.append(([['MgFePerovskite','MgPerovskite'],
                       ['Magnesiowuestite','Wuestite']],
                      [['MgFePerovskite','FePerovskite'],
                       ['Magnesiowuestite','Periclase']]))
    generate_reaction(outdir, 'MgFeSiO4_all', phases, reactions)

    #################################################################
    # OlWaRi MgFeSiO4 reactions
    phases = ['Olivine', 'Wadsleyite', 'Ringwoodite']
    reactions = []
    reactions.append(([['Olivine','Forsterite']],
                      [['Wadsleyite','MgWadsleyite']]))
    reactions.append(([['Olivine','Fayalite']],
                      [['Wadsleyite','FeWadsleyite']]))
    reactions.append(([['Olivine','Forsterite']],
                      [['Ringwoodite','MgRingwoodite']]))
    reactions.append(([['Olivine','Fayalite']],
                      [['Ringwoodite','FeRingwoodite']]))
    reactions.append(([['Wadsleyite','MgWadsleyite']],
                      [['Ringwoodite','MgRingwoodite']]))
    reactions.append(([['Wadsleyite','FeWadsleyite']],
                      [['Ringwoodite','FeRingwoodite']]))
    generate_reaction(outdir, 'MgFeSiO4_olwari', phases, reactions)

    #################################################################
    # All High P MgFeSiO3 reactions
    phases = ['MgFePerovskite', 'MgFePostPerovskite', \
              'Magnesiowuestite', 'Stishovite', 'Seifertite']
             # FIXME: need gt?? and CaCl2??
    reactions = []
    reactions.append((
                      [['MgFePerovskite','MgPerovskite'],
                       ['Magnesiowuestite','Wuestite']],
                      [['MgFePerovskite','FePerovskite'],
                       ['Magnesiowuestite','Periclase']],
                    ))
    reactions.append((
                      [['MgFePostPerovskite','MgPostPerovskite'],
                       ['Magnesiowuestite','Wuestite']],
                      [['MgFePostPerovskite','FePostPerovskite'],
                       ['Magnesiowuestite','Periclase']],
                    ))
    reactions.append((
                      [['Stishovite','Stishovite']],
                      [['Seifertite','Seifertite']],
                    ))
    ## pv -> mw + st|seif
    reactions.append((
                      [['MgFePerovskite','MgPerovskite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    reactions.append((
                      [['MgFePerovskite','MgPerovskite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Seifertite','Seifertite']],
                    ))
    reactions.append((
                      [['MgFePerovskite','FePerovskite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    reactions.append((
                      [['MgFePerovskite','FePerovskite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Seifertite','Seifertite']],
                    ))
    ## pv -> ppv
    reactions.append((
                      [['MgFePerovskite','MgPerovskite']],
                      [['MgFePostPerovskite','MgPostPerovskite']],
                    ))
    reactions.append((
                      [['MgFePerovskite','FePerovskite']],
                      [['MgFePostPerovskite','FePostPerovskite']],
                    ))
    ## ppv -> mw + st|seif
    reactions.append((
                      [['MgFePostPerovskite','MgPostPerovskite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    reactions.append((
                      [['MgFePostPerovskite','MgPostPerovskite']],
                      [['Magnesiowuestite','Periclase'],
                       ['Seifertite','Seifertite']],
                    ))
    reactions.append((
                      [['MgFePostPerovskite','FePostPerovskite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    reactions.append((
                      [['MgFePostPerovskite','FePostPerovskite']],
                      [['Magnesiowuestite','Wuestite'],
                       ['Seifertite','Seifertite']],
                    ))
    generate_reaction(outdir, 'MgFeSiO3_all_highp', phases, reactions)


    #################################################################
    # All Mg2SiO4 reactions
    phases = ['Forsterite', 'MgWadsleyite', 'MgRingwoodite', \
              'MgPerovskite', 'Periclase', 'Stishovite', \
              'MgMajorite', 'MgAkimotoite']
    reactions = []
    ## fo -> mgwa
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['MgWadsleyite','MgWadsleyite']],
                    ))
    ## fo -> mgri
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['MgRingwoodite','MgRingwoodite']],
                    ))
    ## fo -> mgmj + pe
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['MgMajorite','MgMajorite'],
                       ['Periclase','Periclase']],
                    ))
    ## fo -> mgpv + pe
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['MgPerovskite','MgPerovskite'],
                       ['Periclase','Periclase']],
                    ))
    ## fo -> mgak + pe
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['MgAkimotoite','MgAkimotoite'],
                       ['Periclase','Periclase']],
                    ))
    ## fo -> pe + st
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']]
                    ))
    ## mgwa -> mgri
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['MgRingwoodite','MgRingwoodite']],
                    ))
    ## mgwa -> mgmj + pe
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['MgMajorite','MgMajorite'],
                       ['Periclase','Periclase']],
                    ))
    ## mgwa -> mgpv + pe
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['MgPerovskite','MgPerovskite'],
                       ['Periclase','Periclase']],
                    ))
    ## mgwa -> mgak + pe
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['MgAkimotoite','MgAkimotoite'],
                       ['Periclase','Periclase']],
                    ))
    ## mgwa -> pe + st
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']]
                    ))
    ## mgri -> mgmj + pe
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite']],
                      [['MgMajorite','MgMajorite'],
                       ['Periclase','Periclase']],
                    ))
    ## mgri -> mgpv + pe
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite']],
                      [['MgPerovskite','MgPerovskite'],
                       ['Periclase','Periclase']],
                    ))
    ## mgri -> mgak + pe
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite']],
                      [['MgAkimotoite','MgAkimotoite'],
                       ['Periclase','Periclase']],
                    ))
    ## mgri -> pe + st
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']]
                    ))
    ## mgmj -> mgpv
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## mgmj -> mgak
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## mgmj -> pe + st
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## mgpv -> mgak
    reactions.append((
                      [['MgPerovskite','MgPerovskite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## mgpv -> pe + st
    reactions.append((
                      [['MgPerovskite','MgPerovskite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## mgak -> pe + st
    reactions.append((
                      [['MgAkimotoite','MgAkimotoite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    generate_reaction(outdir, 'Mg2SiO4_all', phases, reactions)

    #################################################################
    # All MgSiO3 reactions
    phases = ['Forsterite', 'Quartz', 'Enstatite', \
              'Clinoenstatite', 'HPClinoenstatite', 'MgWadsleyite', \
              'Stishovite', 'MgMajorite', 'MgRingwoodite', \
              'MgAkimotoite', 'MgPerovskite', 'Periclase']
    reactions = []
    ## qtz -> st
    reactions.append((
                      [['Quartz','Quartz']],
                      [['Stishovite','Stishovite']],
                    ))
    ## fo + qtz|st -> en
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Quartz','Quartz']],
                      [['Enstatite','Enstatite']],
                    ))
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Stishovite','Stishovite']],
                      [['Enstatite','Enstatite']],
                    ))
    ## fo + qtz|st -> cen
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Quartz','Quartz']],
                      [['Clinoenstatite','Clinoenstatite']],
                    ))
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Stishovite','Stishovite']],
                      [['Clinoenstatite','Clinoenstatite']],
                    ))
    ## fo + qtz|st -> hpcen
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Quartz','Quartz']],
                      [['HPClinoenstatite','HPClinoenstatite']],
                    ))
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Stishovite','Stishovite']],
                      [['HPClinoenstatite','HPClinoenstatite']],
                    ))
    ## fo (+ qtz) -> wa (+ st)
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['MgWadsleyite','MgWadsleyite']],
                    ))
    ## fo + qtz|st -> mj
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Quartz','Quartz']],
                      [['MgMajorite','MgMajorite']],
                    ))
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Stishovite','Stishovite']],
                      [['MgMajorite','MgMajorite']],
                    ))
    ## fo (+ qtz) -> ri (+ st)
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['MgRingwoodite','MgRingwoodite']],
                    ))
    ## fo + qtz|st -> ak
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Quartz','Quartz']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Stishovite','Stishovite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## fo + qtz|st -> pv
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Quartz','Quartz']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    reactions.append((
                      [['Forsterite','Forsterite'],
                       ['Stishovite','Stishovite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## fo (+ qtz) -> pe + qzt|st
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['Forsterite','Forsterite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## en -> cen
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['Clinoenstatite','Clinoenstatite']],
                    ))
    ## en -> hpcen
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['HPClinoenstatite','HPClinoenstatite']],
                    ))
    ## en -> wa + qtz|st
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## en -> mj
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['MgMajorite','MgMajorite']],
                    ))
    ## en -> ri + qtz|st
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## en -> ak
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## en -> pv
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## en -> pe + qtz|st
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['Enstatite','Enstatite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## cen -> hpcen
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['HPClinoenstatite','HPClinoenstatite']],
                    ))
    ## cen -> wa + qtz|st
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## cen -> mj
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['MgMajorite','MgMajorite']],
                    ))
    ## cen -> ri + qtz|st
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## cen -> ak
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## cen -> pv
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## cen -> pe + qtz|st
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['Clinoenstatite','Clinoenstatite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## hpcen -> wa + qtz|st
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## hpcen -> mj
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['MgMajorite','MgMajorite']],
                    ))
    ## hpcen -> ri + qtz|st
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## hpcen -> ak
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## hpcen -> pv
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## hpcen -> pe + qtz|st
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['HPClinoenstatite','HPClinoenstatite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## wa + qtz|st -> mj
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Quartz','Quartz']],
                      [['MgMajorite','MgMajorite']],
                    ))
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Stishovite','Stishovite']],
                      [['MgMajorite','MgMajorite']],
                    ))
    ## wa (+ st) -> ri (+ st)
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['MgRingwoodite','MgRingwoodite']],
                    ))
    ## wa + qtz|st -> ak
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Quartz','Quartz']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Stishovite','Stishovite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## wa + qtz|st -> pv
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Quartz','Quartz']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite'],
                       ['Stishovite','Stishovite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## wa (+ st) -> pe + qtz|st
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['MgWadsleyite','MgWadsleyite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## mj -> ri + qtz|st
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## mj -> ak
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## mj -> pv
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## mj -> pe + qtz|st
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['MgMajorite','MgMajorite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## ri + qtz|st -> ak
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Quartz','Quartz']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Stishovite','Stishovite']],
                      [['MgAkimotoite','MgAkimotoite']],
                    ))
    ## ri + qtz|st -> pv
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Quartz','Quartz']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite'],
                       ['Stishovite','Stishovite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## ri (+ st) -> pe + qtz|st
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['MgRingwoodite','MgRingwoodite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## ak -> pv
    reactions.append((
                      [['MgAkimotoite','MgAkimotoite']],
                      [['MgPerovskite','MgPerovskite']],
                    ))
    ## ak -> pe + qtz|st
    reactions.append((
                      [['MgAkimotoite','MgAkimotoite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['MgAkimotoite','MgAkimotoite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    ## pv -> pe + qtz|st
    reactions.append((
                      [['MgPerovskite','MgPerovskite']],
                      [['Periclase','Periclase'],
                       ['Quartz','Quartz']],
                    ))
    reactions.append((
                      [['MgPerovskite','MgPerovskite']],
                      [['Periclase','Periclase'],
                       ['Stishovite','Stishovite']],
                    ))
    generate_reaction(outdir, 'MgSiO3_all', phases, reactions)

    #################################################################
    # OlWaRi Mg2SiO4 reactions
    phases = ['Forsterite', 'MgWadsleyite', 'MgRingwoodite', \
              'MgPerovskite', 'Periclase', 'Stishovite']
    reactions = []
    reactions.append(([['Forsterite','Forsterite']],
                      [['MgWadsleyite','MgWadsleyite']]))
    reactions.append(([['Forsterite','Forsterite']],
                      [['MgRingwoodite','MgRingwoodite']]))
    reactions.append(([['MgWadsleyite','MgWadsleyite']],
                      [['MgRingwoodite','MgRingwoodite']]))
    generate_reaction(outdir, 'Mg2SiO4_olwari', phases, reactions)

    #################################################################
    # All MgSiO3-AlAlO3 reactions
    phases = ['MgAlPerovskite', 'MgAlAkimotoite', 'MgWadsleyite', \
              'Stishovite', 'MgAlGarnet', 'HPClinoenstatite', \
              'MgAlOrthopyroxene', 'MgSpinel', 'Quartz']
    reactions = []
    ## pv -> ak
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlAkimotoite', 'MgAkimotoite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlAkimotoite', 'AlAkimotoite']]
                    ))
    ## pv -> wa + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## pv -> gt
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## pv -> hpcen
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## pv -> opx
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlOrthopyroxene', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlOrthopyroxene', 'MgTschermaks']]
                    ))
    ## pv -> sp + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> wa + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> gt
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## ak -> hpcen
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## ak -> opx
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlOrthopyroxene', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlOrthopyroxene', 'MgTschermaks']]
                    ))
    ## ak -> sp + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## wa + qtz|st -> gt
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    ## wa + qtz|st -> hpcen
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## wa + qtz|st -> opx
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlOrthopyroxene', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlOrthopyroxene', 'Enstatite']]
                    ))
    ## wa + st -> sp + qtz - not possible (no Al in wa) so reduce to:
    ## st -> qtz
    reactions.append((
                      [['Stishovite', 'Stishovite']],
                      [['Quartz', 'Quartz']]
                    ))
    ## gt -> hpcen
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## gt -> opx
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['MgAlOrthopyroxene', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlOrthopyroxene', 'MgTschermaks'],
                       ['MgAlOrthopyroxene', 'Enstatite']]
                    ))
    ## gt -> sp + qtz|st - note that mgmj is requried as a product here too
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## hpcen -> opx
    reactions.append((
                      [['HPClinoenstatite', 'HPClinoenstatite']],
                      [['MgAlOrthopyroxene', 'Enstatite']]
                    ))
    ## hpcen -> sp + qtz - not possible, no Al in hpcen
    ## opx -> sp + qtz
    reactions.append((
                      [['MgAlOrthopyroxene', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlOrthopyroxene', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    generate_reaction(outdir, 'MgSiAlAlO3_all', phases, reactions)

    #################################################################
    # All MgSiO3-AlAlO3 reactions
    phases = ['MgAlPerovskite', 'MgAlAkimotoite', 'MgWadsleyite', \
              'Stishovite', 'MgAlGarnet', 'HPClinoenstatite', \
              'MgAlOrthopyroxene2Site', 'MgSpinel', 'Quartz']
    reactions = []
    ## pv -> ak
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlAkimotoite', 'MgAkimotoite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlAkimotoite', 'AlAkimotoite']]
                    ))
    ## pv -> wa + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## pv -> gt
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## pv -> hpcen
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## pv -> opx
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlOrthopyroxene2Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlOrthopyroxene2Site', 'MgTschermaks']]
                    ))
    ## pv -> sp + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> wa + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> gt
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## ak -> hpcen
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## ak -> opx
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlOrthopyroxene2Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlOrthopyroxene2Site', 'MgTschermaks']]
                    ))
    ## ak -> sp + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## wa + qtz|st -> gt
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    ## wa + qtz|st -> hpcen
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## wa + qtz|st -> opx
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlOrthopyroxene2Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlOrthopyroxene2Site', 'Enstatite']]
                    ))
    ## wa + st -> sp + qtz - not possible (no Al in wa) so reduce to:
    ## st -> qtz
    reactions.append((
                      [['Stishovite', 'Stishovite']],
                      [['Quartz', 'Quartz']]
                    ))
    ## gt -> hpcen
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## gt -> opx
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['MgAlOrthopyroxene2Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlOrthopyroxene2Site', 'MgTschermaks'],
                       ['MgAlOrthopyroxene2Site', 'Enstatite']]
                    ))
    ## gt -> sp + qtz|st - note that mgmj is requried as a product here too
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## hpcen -> opx
    reactions.append((
                      [['HPClinoenstatite', 'HPClinoenstatite']],
                      [['MgAlOrthopyroxene2Site', 'Enstatite']]
                    ))
    ## hpcen -> sp + qtz - not possible, no Al in hpcen
    ## opx -> sp + qtz
    reactions.append((
                      [['MgAlOrthopyroxene2Site', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlOrthopyroxene2Site', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    generate_reaction(outdir, 'MgSiAlAlO3_all_2site', phases, reactions)

    #################################################################
    # All MgSiO3-AlAlO3 reactions
    phases = ['MgAlPerovskite', 'MgAlAkimotoite', 'MgWadsleyite', \
              'Stishovite', 'MgAlGarnet', 'HPClinoenstatite', \
              'MgAlOrthopyroxene3Site', 'MgSpinel', 'Quartz']
    reactions = []
    ## pv -> ak
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlAkimotoite', 'MgAkimotoite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlAkimotoite', 'AlAkimotoite']]
                    ))
    ## pv -> wa + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## pv -> gt
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## pv -> hpcen
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## pv -> opx
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlOrthopyroxene3Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlOrthopyroxene3Site', 'MgTschermaks']]
                    ))
    ## pv -> sp + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> wa + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> gt
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## ak -> hpcen
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## ak -> opx
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlOrthopyroxene3Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlOrthopyroxene3Site', 'MgTschermaks']]
                    ))
    ## ak -> sp + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## wa + qtz|st -> gt
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    ## wa + qtz|st -> hpcen
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## wa + qtz|st -> opx
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlOrthopyroxene3Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlOrthopyroxene3Site', 'Enstatite']]
                    ))
    ## wa + st -> sp + qtz - not possible (no Al in wa) so reduce to:
    ## st -> qtz
    reactions.append((
                      [['Stishovite', 'Stishovite']],
                      [['Quartz', 'Quartz']]
                    ))
    ## gt -> hpcen
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## gt -> opx
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['MgAlOrthopyroxene3Site', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlOrthopyroxene3Site', 'MgTschermaks'],
                       ['MgAlOrthopyroxene3Site', 'Enstatite']]
                    ))
    ## gt -> sp + qtz|st - note that mgmj is requried as a product here too
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## hpcen -> opx
    reactions.append((
                      [['HPClinoenstatite', 'HPClinoenstatite']],
                      [['MgAlOrthopyroxene3Site', 'Enstatite']]
                    ))
    ## hpcen -> sp + qtz - not possible, no Al in hpcen
    ## opx -> sp + qtz
    reactions.append((
                      [['MgAlOrthopyroxene3Site', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlOrthopyroxene3Site', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    generate_reaction(outdir, 'MgSiAlAlO3_all_3site', phases, reactions)

    #################################################################
    # All MgSiO3-AlAlO3 reactions
    phases = ['MgAlPerovskite', 'MgAlAkimotoite', 'MgWadsleyite', \
              'Stishovite', 'MgAlGarnet', 'HPClinoenstatite', \
              'MgAlOrthopyroxene3SiteB', 'MgSpinel', 'Quartz']
    reactions = []
    ## pv -> ak
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlAkimotoite', 'MgAkimotoite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlAkimotoite', 'AlAkimotoite']]
                    ))
    ## pv -> wa + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## pv -> gt
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## pv -> hpcen
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## pv -> opx
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite']],
                      [['MgAlOrthopyroxene3SiteB', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgAlOrthopyroxene3SiteB', 'MgTschermaks']]
                    ))
    ## pv -> sp + qtz|st
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlPerovskite', 'MgPerovskite'],
                       ['MgAlPerovskite', 'AlPerovskite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> wa + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## ak -> gt
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlGarnet', 'Pyrope']]
                    ))
    ## ak -> hpcen
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## ak -> opx
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite']],
                      [['MgAlOrthopyroxene3SiteB', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgAlOrthopyroxene3SiteB', 'MgTschermaks']]
                    ))
    ## ak -> sp + qtz|st
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlAkimotoite', 'MgAkimotoite'],
                       ['MgAlAkimotoite', 'AlAkimotoite']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## wa + qtz|st -> gt
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlGarnet', 'MgMajorite']]
                    ))
    ## wa + qtz|st -> hpcen
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## wa + qtz|st -> opx
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Quartz', 'Quartz']],
                      [['MgAlOrthopyroxene3SiteB', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgWadsleyite', 'MgWadsleyite'],
                       ['Stishovite', 'Stishovite']],
                      [['MgAlOrthopyroxene3SiteB', 'Enstatite']]
                    ))
    ## wa + st -> sp + qtz - not possible (no Al in wa) so reduce to:
    ## st -> qtz
    reactions.append((
                      [['Stishovite', 'Stishovite']],
                      [['Quartz', 'Quartz']]
                    ))
    ## gt -> hpcen
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['HPClinoenstatite', 'HPClinoenstatite']]
                    ))
    ## gt -> opx
    reactions.append((
                      [['MgAlGarnet', 'MgMajorite']],
                      [['MgAlOrthopyroxene3SiteB', 'Enstatite']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlOrthopyroxene3SiteB', 'MgTschermaks'],
                       ['MgAlOrthopyroxene3SiteB', 'Enstatite']]
                    ))
    ## gt -> sp + qtz|st - note that mgmj is requried as a product here too
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlGarnet', 'Pyrope']],
                      [['MgAlGarnet', 'MgMajorite'],
                       ['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    ## hpcen -> opx
    reactions.append((
                      [['HPClinoenstatite', 'HPClinoenstatite']],
                      [['MgAlOrthopyroxene3SiteB', 'Enstatite']]
                    ))
    ## hpcen -> sp + qtz - not possible, no Al in hpcen
    ## opx -> sp + qtz
    reactions.append((
                      [['MgAlOrthopyroxene3SiteB', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Quartz', 'Quartz']]
                    ))
    reactions.append((
                      [['MgAlOrthopyroxene3SiteB', 'MgTschermaks']],
                      [['MgSpinel', 'MgSpinel'],
                       ['Stishovite', 'Stishovite']]
                    ))
    generate_reaction(outdir, 'MgSiAlAlO3_all_3siteB', phases, reactions)

    #################################################################
    # All Low P Fe2SiO4 reactions
    phases = ['Fayalite', 'Wuestite', 'Quartz', \
              'Ferrosilite', 'FeRingwoodite', 'Stishovite']
    reactions = []
    ## fa -> wu + qtz
    reactions.append((
                      [['Fayalite','Fayalite']],
                      [['Wuestite','Wuestite'],
                       ['Quartz','Quartz']],
                    ))
    ## fa -> fs + wu
    reactions.append((
                      [['Fayalite','Fayalite']],
                      [['Ferrosilite','Ferrosilite'],
                       ['Wuestite','Wuestite']],
                    ))
    ## fa -> ri
    reactions.append((
                      [['Fayalite','Fayalite']],
                      [['FeRingwoodite','FeRingwoodite']],
                    ))
    ## fa -> wu + st
    reactions.append((
                      [['Fayalite','Fayalite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## wu + qtz -> fs (+ wu)
    reactions.append((
                      [['Wuestite','Wuestite'],
                       ['Quartz','Quartz']],
                      [['Ferrosilite','Ferrosilite']]
                    ))
    ## wu + qtz -> ri
    reactions.append((
                      [['Wuestite','Wuestite'],
                       ['Quartz','Quartz']],
                      [['FeRingwoodite','FeRingwoodite']],
                    ))
    ## (wu +) qtz -> (wu +) st
    reactions.append((
                      [['Quartz','Quartz']],
                      [['Stishovite','Stishovite']],
                    ))
    ## fs + wu -> ri
    reactions.append((
                      [['Ferrosilite','Ferrosilite'],
                       ['Wuestite','Wuestite']],
                      [['FeRingwoodite','FeRingwoodite']],
                    ))
    ## fs (+ wu) -> wu + st
    reactions.append((
                      [['Ferrosilite','Ferrosilite']],
                      [['Stishovite','Stishovite'],
                       ['Wuestite','Wuestite']],
                    ))
    ## ri -> wu + st
    reactions.append((
                      [['FeRingwoodite','FeRingwoodite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    generate_reaction(outdir, 'Fe2SiO4_all', phases, reactions)

    #################################################################
    # All Low P FeSiO3 reactions
    phases = ['Fayalite', 'Wuestite', 'Quartz', \
              'Ferrosilite', 'HPClinoferrosilite', 'FeRingwoodite', \
              'Stishovite']
    reactions = []
    ## fa (+ qtz) -> wu + qtz
    reactions.append((
                      [['Fayalite','Fayalite']],
                      [['Wuestite','Wuestite'],
                       ['Quartz','Quartz']],
                    ))
    ## fa + qtz -> fs
    reactions.append((
                      [['Fayalite','Fayalite'],
                       ['Quartz','Quartz']],
                      [['Ferrosilite','Ferrosilite']],
                    ))
    ## fa + qtz -> hpcfs
    reactions.append((
                      [['Fayalite','Fayalite'],
                       ['Quartz','Quartz']],
                      [['HPClinoferrosilite','HPClinoferrosilite']],
                    ))
    ## fa + qtz -> ri + st (2 rxns)
    reactions.append((
                      [['Fayalite','Fayalite']],
                      [['FeRingwoodite','FeRingwoodite']],
                    ))
    reactions.append((
                      [['Quartz','Quartz']],
                      [['Stishovite','Stishovite']],
                    ))
    ## fa (+ qtz) -> wu + st
    reactions.append((
                      [['Fayalite','Fayalite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## wu + qtz -> fs
    reactions.append((
                      [['Wuestite','Wuestite'],
                       ['Quartz','Quartz']],
                      [['Ferrosilite','Ferrosilite']],
                    ))
    ## wu + qtz -> hpcfs
    reactions.append((
                      [['Wuestite','Wuestite'],
                       ['Quartz','Quartz']],
                      [['HPClinoferrosilite','HPClinoferrosilite']],
                    ))
    ## wu + qtz -> ri (+ st)
    reactions.append((
                      [['Wuestite','Wuestite'],
                       ['Quartz','Quartz']],
                      [['FeRingwoodite','FeRingwoodite']],
                    ))
    ## (wu +) qtz -> (wu +) st - already above
    ## fs -> hpcfs
    reactions.append((
                      [['Ferrosilite','Ferrosilite']],
                      [['HPClinoferrosilite','HPClinoferrosilite']],
                    ))
    ## fs -> ri + st
    reactions.append((
                      [['Ferrosilite','Ferrosilite']],
                      [['FeRingwoodite','FeRingwoodite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## fs -> wu + st
    reactions.append((
                      [['Ferrosilite','Ferrosilite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## hpcfs -> ri + st
    reactions.append((
                      [['HPClinoferrosilite','HPClinoferrosilite']],
                      [['FeRingwoodite','FeRingwoodite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## hpcfs -> wu + st
    reactions.append((
                      [['HPClinoferrosilite','HPClinoferrosilite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    ## ri (+ st) -> wu + st
    reactions.append((
                      [['FeRingwoodite','FeRingwoodite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))

    generate_reaction(outdir, 'FeSiO3_all', phases, reactions)

    #################################################################
    # All High P MgSiO3 reactions
    phases = ['MgPerovskite', 'MgPostPerovskite']
    reactions = []
    ## pv -> ppv
    reactions.append((
                      [['MgPerovskite','MgPerovskite']],
                      [['MgPostPerovskite','MgPostPerovskite']],
                    ))
    generate_reaction(outdir, 'MgSiO3_all_highp', phases, reactions)

    #################################################################
    # All High P FeSiO3 reactions
    phases = ['Wuestite', 'FePerovskite',  'FePostPerovskite', \
              'Stishovite', 'Seifertite'] # FIXME: missing CaCl2
    reactions = []
    ## st -> seif
    reactions.append((
                      [['Stishovite','Stishovite']],
                      [['Seifertite','Seifertite']],
                    ))
    ## pv -> ppv
    reactions.append((
                      [['FePerovskite','FePerovskite']],
                      [['FePostPerovskite','FePostPerovskite']],
                    ))
    ## pv -> wu + st|seif
    reactions.append((
                      [['FePerovskite','FePerovskite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    reactions.append((
                      [['FePerovskite','FePerovskite']],
                      [['Wuestite','Wuestite'],
                       ['Seifertite','Seifertite']],
                    ))
    ## ppv -> wu + st|seif
    reactions.append((
                      [['FePostPerovskite','FePostPerovskite']],
                      [['Wuestite','Wuestite'],
                       ['Stishovite','Stishovite']],
                    ))
    reactions.append((
                      [['FePostPerovskite','FePostPerovskite']],
                      [['Wuestite','Wuestite'],
                       ['Seifertite','Seifertite']],
                    ))
    generate_reaction(outdir, 'FeSiO3_all_highp', phases, reactions)

    #################################################################
    # All High P AlAlO3 reactions
    phases = ['AlAkimotoite', 'AlPerovskite',  'AlPostPerovskite']
    reactions = []
    ## ak -> pv
    reactions.append((
                      [['AlAkimotoite','AlAkimotoite']],
                      [['AlPerovskite','AlPerovskite']],
                    ))
    ## ak -> ppv
    reactions.append((
                      [['AlAkimotoite','AlAkimotoite']],
                      [['AlPostPerovskite','AlPostPerovskite']],
                    ))
    ## pv -> ppv
    reactions.append((
                      [['AlPerovskite','AlPerovskite']],
                      [['AlPostPerovskite','AlPostPerovskite']],
                    ))
    generate_reaction(outdir, 'AlAlO3_all_highp', phases, reactions)

    #################################################################
    # All High P SiO2 reactions
    phases = ['Stishovite', 'Seifertite'] # FIXME: missing CaCl2!
    reactions = []
    ## pv -> ppv
    reactions.append((
                      [['Stishovite','Stishovite']],
                      [['Seifertite','Seifertite']],
                    ))
    generate_reaction(outdir, 'SiO2_all_highp', phases, reactions)

    #################################################################

def generate_reaction(outdir, name, phases, reactions):
    try:
        os.mkdir(outdir)
    except FileExistsError:
        pass
    phases = [ph+"_slb_ph" for ph in phases]

    slbrx = SLBReactions(name+'_slb_rx', len(reactions), phases, dbpath, reference)
    for reaction in reactions:
        reactants = [[[ph+"_slb_ph", em+"_slb_em"] for ph, em in reaction[i]] for i in range(2)]
        slbrx.add_reaction(*reactants)
    slbrx.tofile(outdir)

    slbrx_reg = SLBReactions(name+'_reg_slb_rx', len(reactions), phases, dbpath, reference, avail_type='regularized')
    for reaction in reactions:
        reactants = [[[ph+"_slb_ph", em+"_slb_em"] for ph, em in reaction[i]] for i in range(2)]
        slbrx_reg.add_reaction(*reactants)
    slbrx_reg.tofile(outdir)

if __name__ == "__main__":
    import argparse
    import os

    parser = argparse.ArgumentParser( \
                           description="""Generate rxmls for SLB thermodynamic database.""")
    parser.add_argument('-o', '--outdir', action='store', metavar='outdir', 
                        default=os.path.join(os.path.pardir, 'database', 'reactions'), type=str, required=False,
                        help='Output directory for rxml files (defaults to ../database/reactions relative to script).')
    args = parser.parse_args()

    generate_reactions(args.outdir)


