#!/usr/bin/env bash

usage()
{
    echo "usage: generate_database_source [-b] [-h] "
}

full_path=$(realpath $0)
script_path=$(dirname $full_path)
repo_path=$(dirname $script_path)
db_path=$repo_path/database

FLAGS="--just_src -z -i"
while [ -n "$1" ]; do
    case $1 in
        -b )           FLAGS="-i install"
                       ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     echo "ERROR: Unknown option $1"
                                usage
                                exit 1
                                ;;
    esac
    shift
done

cd $db_path
tcg_builddb --calibfile params.csv $FLAGS -l tcg_slb_database

